INSERT INTO researchportal.conference VALUES ( 'National Conference on Industrial Engineering and Technology Management', 'National', 'Mumbai', 2016);
INSERT INTO researchportal.conference VALUES ( 'International Conference on Business, Economics, Social Science & Humanities', 'International', 'New Delhi', 2014);
INSERT INTO researchportal.conference VALUES ( 'International Conference on Recent Trends in Advanced Engineering', 'International', 'Bengaluru', 2015);
INSERT INTO researchportal.conference VALUES ( 'International Conference on Sustainable Energy Engineering', 'International', 'Perth', 2016);
INSERT INTO researchportal.conference VALUES ( 'IEEE International Conference on Integrated Circuits and Microsystems', 'International', 'Chengdu', 2015);
INSERT INTO researchportal.conference VALUES ( '2nd International Conference on Communication and Network Security', 'International', 'Singapore', 2012);
INSERT INTO researchportal.conference VALUES ( 'Soft Computing: Theories and Applications', 'National', 'Jaipur', 2017);
INSERT INTO researchportal.conference VALUES ( 'Amman 5th International Conference on “Engineering & Technology, Computer, Basic & Applied Sciences”', 'International', 'Amman', 2017);
INSERT INTO researchportal.conference VALUES ( 'International Conference on Advanced Computing and Intelligent Engineering', 'International', 'Bhubaneshwar', 2015);
INSERT INTO researchportal.conference VALUES ( '3rd International Conference on Advances in Engineering Sciences and Applied Mathematics', 'International', 'Kuala Lampur', 2013);
