insert into researchportal.professorinterests (prof_id, interest) values ('25-7998231', 'HPC');
insert into researchportal.professorinterests (prof_id, interest) values ('25-7998231', 'Robotics');
insert into researchportal.professorinterests (prof_id, interest) values ('85-5180507', 'HPC');
insert into researchportal.professorinterests (prof_id, interest) values ('21-0140456', 'Embedded Hardware Design');
insert into researchportal.professorinterests (prof_id, interest) values ('08-3701701', 'COmputational Physics');
insert into researchportal.professorinterests (prof_id, interest) values ('82-8497674', 'Algorithms');
insert into researchportal.professorinterests (prof_id, interest) values ('98-9799272', 'Satellite communication');
insert into researchportal.professorinterests (prof_id, interest) values ('54-7938725', 'Algorithms');
insert into researchportal.professorinterests (prof_id, interest) values ('09-9841653', 'HPC');
insert into researchportal.professorinterests (prof_id, interest) values ('30-2784780', 'Mobile Computing');
insert into researchportal.professorinterests (prof_id, interest) values ('09-7635725', 'HPC');
insert into researchportal.professorinterests (prof_id, interest) values ('69-7838304', 'Robotics');
insert into researchportal.professorinterests (prof_id, interest) values ('09-9841653', 'Embedded Hardware Design');
insert into researchportal.professorinterests (prof_id, interest) values ('09-0885116', 'Internet of Things');
insert into researchportal.professorinterests (prof_id, interest) values ('02-3178485', 'Algorithms');
insert into researchportal.professorinterests (prof_id, interest) values ('69-7838304', 'Satellite communication');
insert into researchportal.professorinterests (prof_id, interest) values ('61-4998878', 'HPC');
insert into researchportal.professorinterests (prof_id, interest) values ('19-1624032', 'Economics');
insert into researchportal.professorinterests (prof_id, interest) values ('62-7820841', 'Satellite communication');
insert into researchportal.professorinterests (prof_id, interest) values ('51-8185424', 'Satellite communication');
insert into researchportal.professorinterests (prof_id, interest) values ('34-9056688', 'Mobile Computing');
insert into researchportal.professorinterests (prof_id, interest) values ('79-0566677', 'Machine Learning');
insert into researchportal.professorinterests (prof_id, interest) values ('42-8531419', 'Satellite communication');
insert into researchportal.professorinterests (prof_id, interest) values ('37-3511634', 'Economics');
insert into researchportal.professorinterests (prof_id, interest) values ('82-8497674', 'HPC');
insert into researchportal.professorinterests (prof_id, interest) values ('98-9799272', 'Machine Learning');
insert into researchportal.professorinterests (prof_id, interest) values ('09-0885116', 'Satellite communication');
insert into researchportal.professorinterests (prof_id, interest) values ('05-4844263', 'Robotics');
insert into researchportal.professorinterests (prof_id, interest) values ('05-4844263', 'Algorithms');
insert into researchportal.professorinterests (prof_id, interest) values ('69-7838304', 'Mobile Computing');
insert into researchportal.professorinterests (prof_id, interest) values ('48-4969228', 'Machine Learning');
insert into researchportal.professorinterests (prof_id, interest) values ('74-5656465', 'Mobile Computing');
insert into researchportal.professorinterests (prof_id, interest) values ('02-3178485', 'Economics');
insert into researchportal.professorinterests (prof_id, interest) values ('62-7820841', 'Machine Learning');
insert into researchportal.professorinterests (prof_id, interest) values ('71-7349834', 'Internet of Things');
insert into researchportal.professorinterests (prof_id, interest) values ('19-1624032', 'Internet of Things');
insert into researchportal.professorinterests (prof_id, interest) values ('50-2204284', 'COmputational Physics');
insert into researchportal.professorinterests (prof_id, interest) values ('54-0272636', 'HPC');
insert into researchportal.professorinterests (prof_id, interest) values ('60-1677694', 'Mobile Computing');
insert into researchportal.professorinterests (prof_id, interest) values ('54-7938725', 'Mobile Computing');
insert into researchportal.professorinterests (prof_id, interest) values ('79-0566677', 'Robotics');
insert into researchportal.professorinterests (prof_id, interest) values ('34-9056688', 'Economics');
insert into researchportal.professorinterests (prof_id, interest) values ('45-3795863', 'COmputational Physics');
insert into researchportal.professorinterests (prof_id, interest) values ('82-8497674', 'Embedded Hardware Design');
insert into researchportal.professorinterests (prof_id, interest) values ('25-7998231', 'Satellite communication');
insert into researchportal.professorinterests (prof_id, interest) values ('20-2098557', 'COmputational Physics');
insert into researchportal.professorinterests (prof_id, interest) values ('54-5770962', 'Robotics');
insert into researchportal.professorinterests (prof_id, interest) values ('08-3701701', 'Economics');
insert into researchportal.professorinterests (prof_id, interest) values ('16-9623337', 'Satellite communication');
insert into researchportal.professorinterests (prof_id, interest) values ('25-7998231', 'Machine Learning');
