insert into researchportal.professor (prof_id, prof_name, dept_id, designation, h_index, i_index) values ('68-1979109', 'Teresa Patterson', 3, 'associate professor', 64, 118);
insert into researchportal.professor (prof_id, prof_name, dept_id, designation, h_index, i_index) values ('30-4510804', 'Karen Bryant', 2, 'professor', 34, 97);
insert into researchportal.professor (prof_id, prof_name, dept_id, designation, h_index, i_index) values ('60-1677694', 'Laura Torres', 3, 'associate professor', 100, 58);
insert into researchportal.professor (prof_id, prof_name, dept_id, designation, h_index, i_index) values ('45-3795863', 'Ruth Young', 1, 'associate professor', 187, 62);
insert into researchportal.professor (prof_id, prof_name, dept_id, designation, h_index, i_index) values ('82-8497674', 'Anna Brooks', 2, 'assistant professor', 25, 52);
insert into researchportal.professor (prof_id, prof_name, dept_id, designation, h_index, i_index) values ('05-4844263', 'Jean Campbell', 2, 'assistant professor', 184, 166);
insert into researchportal.professor (prof_id, prof_name, dept_id, designation, h_index, i_index) values ('02-3178485', 'Ruth Foster', 3, 'assistant professor', 71, 200);
insert into researchportal.professor (prof_id, prof_name, dept_id, designation, h_index, i_index) values ('74-5656465', 'Andrea Armstrong', 3, 'assistant professor', 189, 91);
insert into researchportal.professor (prof_id, prof_name, dept_id, designation, h_index, i_index) values ('18-2033468', 'Norma Ross', 1, 'professor', 26, 102);
insert into researchportal.professor (prof_id, prof_name, dept_id, designation, h_index, i_index) values ('14-7569123', 'Anna Webb', 1, 'associate professor', 190, 61);
insert into researchportal.professor (prof_id, prof_name, dept_id, designation, h_index, i_index) values ('40-4426510', 'Wayne Brown', 3, 'professor', 161, 153);
insert into researchportal.professor (prof_id, prof_name, dept_id, designation, h_index, i_index) values ('62-9496247', 'Jessica Ramirez', 3, 'associate professor', 94, 164);
insert into researchportal.professor (prof_id, prof_name, dept_id, designation, h_index, i_index) values ('08-3701701', 'Barbara Olson', 1, 'associate professor', 103, 86);
insert into researchportal.professor (prof_id, prof_name, dept_id, designation, h_index, i_index) values ('25-7998231', 'Thomas Gilbert', 2, 'associate professor', 197, 15);
insert into researchportal.professor (prof_id, prof_name, dept_id, designation, h_index, i_index) values ('69-7838304', 'Brian Torres', 3, 'professor', 126, 130);
insert into researchportal.professor (prof_id, prof_name, dept_id, designation, h_index, i_index) values ('21-0140456', 'Wanda Hanson', 2, 'associate professor', 75, 182);
insert into researchportal.professor (prof_id, prof_name, dept_id, designation, h_index, i_index) values ('37-3511634', 'Helen Thompson', 1, 'associate professor', 11, 17);
insert into researchportal.professor (prof_id, prof_name, dept_id, designation, h_index, i_index) values ('30-2784780', 'Ernest Medina', 2, 'assistant professor', 151, 125);
insert into researchportal.professor (prof_id, prof_name, dept_id, designation, h_index, i_index) values ('51-8185424', 'Michael Wood', 3, 'associate professor', 156, 47);
insert into researchportal.professor (prof_id, prof_name, dept_id, designation, h_index, i_index) values ('42-8531419', 'Chris Grant', 3, 'professor', 192, 88);
insert into researchportal.professor (prof_id, prof_name, dept_id, designation, h_index, i_index) values ('13-0103182', 'Harry Hawkins', 1, 'associate professor', 103, 158);
insert into researchportal.professor (prof_id, prof_name, dept_id, designation, h_index, i_index) values ('54-7938725', 'Katherine Bradley', 3, 'associate professor', 33, 156);
insert into researchportal.professor (prof_id, prof_name, dept_id, designation, h_index, i_index) values ('16-9623337', 'Roger Edwards', 2, 'associate professor', 123, 53);
insert into researchportal.professor (prof_id, prof_name, dept_id, designation, h_index, i_index) values ('71-7349834', 'Walter Gonzalez', 2, 'associate professor', 39, 119);
insert into researchportal.professor (prof_id, prof_name, dept_id, designation, h_index, i_index) values ('25-9951410', 'Katherine Green', 2, 'professor', 86, 150);
insert into researchportal.professor (prof_id, prof_name, dept_id, designation, h_index, i_index) values ('19-1785806', 'Joshua Wright', 1, 'assistant professor', 12, 93);
insert into researchportal.professor (prof_id, prof_name, dept_id, designation, h_index, i_index) values ('63-8244015', 'Jonathan Robinson', 3, 'assistant professor', 187, 182);
insert into researchportal.professor (prof_id, prof_name, dept_id, designation, h_index, i_index) values ('09-9841653', 'Ralph Bradley', 3, 'professor', 180, 11);
insert into researchportal.professor (prof_id, prof_name, dept_id, designation, h_index, i_index) values ('78-7319786', 'Eugene Robertson', 3, 'associate professor', 40, 181);
insert into researchportal.professor (prof_id, prof_name, dept_id, designation, h_index, i_index) values ('61-6727884', 'Phyllis Nguyen', 3, 'assistant professor', 200, 91);
insert into researchportal.professor (prof_id, prof_name, dept_id, designation, h_index, i_index) values ('88-5796340', 'Carlos Wheeler', 1, 'assistant professor', 37, 10);
insert into researchportal.professor (prof_id, prof_name, dept_id, designation, h_index, i_index) values ('54-0272636', 'Daniel Graham', 1, 'assistant professor', 70, 58);
insert into researchportal.professor (prof_id, prof_name, dept_id, designation, h_index, i_index) values ('65-2916017', 'Andrea Walker', 3, 'professor', 163, 137);
insert into researchportal.professor (prof_id, prof_name, dept_id, designation, h_index, i_index) values ('09-7635725', 'Harold Wells', 3, 'professor', 27, 114);
insert into researchportal.professor (prof_id, prof_name, dept_id, designation, h_index, i_index) values ('22-9434553', 'Melissa Martinez', 2, 'associate professor', 94, 150);
insert into researchportal.professor (prof_id, prof_name, dept_id, designation, h_index, i_index) values ('43-6561183', 'Harry Reed', 1, 'professor', 3, 164);
insert into researchportal.professor (prof_id, prof_name, dept_id, designation, h_index, i_index) values ('48-4969228', 'Linda King', 3, 'associate professor', 119, 169);
insert into researchportal.professor (prof_id, prof_name, dept_id, designation, h_index, i_index) values ('79-0566677', 'Helen Gordon', 1, 'assistant professor', 68, 160);
insert into researchportal.professor (prof_id, prof_name, dept_id, designation, h_index, i_index) values ('19-1624032', 'Raymond Jenkins', 2, 'professor', 68, 135);
insert into researchportal.professor (prof_id, prof_name, dept_id, designation, h_index, i_index) values ('34-9056688', 'Annie Hansen', 2, 'assistant professor', 181, 2);
insert into researchportal.professor (prof_id, prof_name, dept_id, designation, h_index, i_index) values ('91-0505651', 'Johnny Larson', 3, 'assistant professor', 63, 184);
insert into researchportal.professor (prof_id, prof_name, dept_id, designation, h_index, i_index) values ('54-5770962', 'Chris Hayes', 1, 'professor', 180, 36);
insert into researchportal.professor (prof_id, prof_name, dept_id, designation, h_index, i_index) values ('20-2098557', 'Richard Anderson', 2, 'associate professor', 107, 66);
insert into researchportal.professor (prof_id, prof_name, dept_id, designation, h_index, i_index) values ('60-9263644', 'Stephen Stanley', 3, 'assistant professor', 28, 106);
insert into researchportal.professor (prof_id, prof_name, dept_id, designation, h_index, i_index) values ('50-2204284', 'Robin Berry', 2, 'associate professor', 11, 101);
insert into researchportal.professor (prof_id, prof_name, dept_id, designation, h_index, i_index) values ('62-7820841', 'Ernest Weaver', 3, 'associate professor', 109, 31);
insert into researchportal.professor (prof_id, prof_name, dept_id, designation, h_index, i_index) values ('98-9799272', 'Beverly Meyer', 1, 'professor', 61, 36);
insert into researchportal.professor (prof_id, prof_name, dept_id, designation, h_index, i_index) values ('85-5180507', 'Christopher Sullivan', 1, 'assistant professor', 11, 108);
insert into researchportal.professor (prof_id, prof_name, dept_id, designation, h_index, i_index) values ('61-4998878', 'Shawn Gonzalez', 2, 'associate professor', 169, 196);
insert into researchportal.professor (prof_id, prof_name, dept_id, designation, h_index, i_index) values ('09-0885116', 'Amanda Butler', 3, 'associate professor', 104, 176);
