insert into researchportal.project (proj_id, proj_name, proj_domain, inception_date, conclusion_date, status) values (1, 'Jonah', 'Economics', '2006-06-23', '2009-12-28', 'Completed');
insert into researchportal.project (proj_id, proj_name, proj_domain, inception_date, conclusion_date, status) values (2, 'Casanova', 'hpc', '2005-06-23', NULL, 'Ongoing');
insert into researchportal.project (proj_id, proj_name, proj_domain, inception_date, conclusion_date, status) values (3, 'Romeo', 'Algorithms', '2004-08-06', '2015-03-13', 'Completed');
insert into researchportal.project (proj_id, proj_name, proj_domain, inception_date, conclusion_date, status) values (4, 'Sahara', 'Electronics', '2003-01-02', '2009-04-10', 'Completed');
insert into researchportal.project (proj_id, proj_name, proj_domain, inception_date, conclusion_date, status) values (5, 'Cyclone', 'hpc', '2008-04-04', NULL, 'Ongoing');
insert into researchportal.project (proj_id, proj_name, proj_domain, inception_date, conclusion_date, status) values (6, 'Cinnamon', 'Computational Physics', '2003-08-05', '2010-01-24', 'Completed');
insert into researchportal.project (proj_id, proj_name, proj_domain, inception_date, conclusion_date, status) values (7, 'Indigo', 'Mobile Development', '2005-06-09', '2012-01-13', 'Stalled');
insert into researchportal.project (proj_id, proj_name, proj_domain, inception_date, conclusion_date, status) values (8, 'Duracell', 'Image Processing', '2006-11-05', NULL, 'Upcoming');
insert into researchportal.project (proj_id, proj_name, proj_domain, inception_date, conclusion_date, status) values (9, 'Darwin', 'Machine Learning', '2002-12-07', '2009-07-21', 'Stalled');
insert into researchportal.project (proj_id, proj_name, proj_domain, inception_date, conclusion_date, status) values (10, 'Moonshine', 'Algorithms', '2003-03-02', '2016-01-21', 'Completed');
insert into researchportal.project (proj_id, proj_name, proj_domain, inception_date, conclusion_date, status) values (11, 'Orion', 'Mobile Development', '2008-09-14', '2009-10-04', 'Completed');
insert into researchportal.project (proj_id, proj_name, proj_domain, inception_date, conclusion_date, status) values (12, 'Mad Hatter', 'Economics', '2008-03-16', NULL, 'Ongoing');
insert into researchportal.project (proj_id, proj_name, proj_domain, inception_date, conclusion_date, status) values (13, 'Firefly', 'Machine Learning', '2005-09-05', '2015-05-12', 'Stalled');
insert into researchportal.project (proj_id, proj_name, proj_domain, inception_date, conclusion_date, status) values (14, 'Hydra', 'Embedded Hardware Design', NULL, NULL, 'Upcoming');
insert into researchportal.project (proj_id, proj_name, proj_domain, inception_date, conclusion_date, status) values (15, 'Firestorm', 'Internet of Things', NULL, NULL, 'Upcoming');
insert into researchportal.project (proj_id, proj_name, proj_domain, inception_date, conclusion_date, status) values (16, 'Fester', 'Satellite Communication', '2008-01-24', NULL, 'Ongoing');
insert into researchportal.project (proj_id, proj_name, proj_domain, inception_date, conclusion_date, status) values (17, 'Zircon', 'Internet of Things', NULL, NULL, 'Upcoming');
insert into researchportal.project (proj_id, proj_name, proj_domain, inception_date, conclusion_date, status) values (18, 'Bigfish', 'Data Science', NULL, NULL, 'Upcoming');
insert into researchportal.project (proj_id, proj_name, proj_domain, inception_date, conclusion_date, status) values (19, 'Wide Stringer', 'Mobile Development', '2006-05-07', NULL, 'Ongoing');
insert into researchportal.project (proj_id, proj_name, proj_domain, inception_date, conclusion_date, status) values (20, 'Edison', 'Data Science', NULL, NULL, 'Upcoming');
