INSERT INTO studentskills VALUES ('5              ', 'OpenMP');
INSERT INTO studentskills VALUES ('12             ', 'Cryptography');
INSERT INTO studentskills VALUES ('47             ', 'Microcontroller');
INSERT INTO studentskills VALUES ('41             ', 'Python');
INSERT INTO studentskills VALUES ('11             ', 'DBMS');
INSERT INTO studentskills VALUES ('16             ', 'MPI');
INSERT INTO studentskills VALUES ('30             ', 'Linux Tools');
INSERT INTO studentskills VALUES ('78             ', 'MPI');
INSERT INTO studentskills VALUES ('21             ', 'Cryptography');
INSERT INTO studentskills VALUES ('84             ', 'MPI');
INSERT INTO studentskills VALUES ('85             ', 'Linux Tools');
INSERT INTO studentskills VALUES ('75             ', 'Data Structures');
INSERT INTO studentskills VALUES ('53             ', 'C');
INSERT INTO studentskills VALUES ('1              ', 'System Softwares');
INSERT INTO studentskills VALUES ('82             ', 'MPI');
INSERT INTO studentskills VALUES ('31             ', 'Python');
INSERT INTO studentskills VALUES ('40             ', 'Microcontroller');
INSERT INTO studentskills VALUES ('54             ', 'Hadoop');
INSERT INTO studentskills VALUES ('67             ', 'Networking Tools');
INSERT INTO studentskills VALUES ('83             ', 'Hadoop');
INSERT INTO studentskills VALUES ('31             ', 'OpenMP');
INSERT INTO studentskills VALUES ('40             ', 'Python');
INSERT INTO studentskills VALUES ('87             ', 'MATLAB');
INSERT INTO studentskills VALUES ('64             ', 'MPI');
INSERT INTO studentskills VALUES ('14             ', 'Cryptography');
INSERT INTO studentskills VALUES ('6              ', 'OpenMP');
INSERT INTO studentskills VALUES ('9              ', 'OpenMP');
INSERT INTO studentskills VALUES ('12             ', 'OpenMP');
INSERT INTO studentskills VALUES ('13             ', 'OpenMP');
INSERT INTO studentskills VALUES ('19             ', 'OpenMP');
INSERT INTO studentskills VALUES ('22             ', 'OpenMP');
INSERT INTO studentskills VALUES ('25             ', 'OpenMP');
INSERT INTO studentskills VALUES ('26             ', 'OpenMP');
INSERT INTO studentskills VALUES ('27             ', 'OpenMP');
INSERT INTO studentskills VALUES ('33             ', 'OpenMP');
INSERT INTO studentskills VALUES ('39             ', 'OpenMP');
INSERT INTO studentskills VALUES ('100            ', 'Cryptography');
INSERT INTO studentskills VALUES ('64             ', 'Data Structures');
INSERT INTO studentskills VALUES ('3              ', 'Android');
INSERT INTO studentskills VALUES ('23             ', 'Python');
INSERT INTO studentskills VALUES ('5              ', 'Linux Tools');
INSERT INTO studentskills VALUES ('27             ', 'MATLAB');
INSERT INTO studentskills VALUES ('80             ', 'Data Structures');
INSERT INTO studentskills VALUES ('13             ', 'Cryptography');
INSERT INTO studentskills VALUES ('31             ', 'Hadoop');
INSERT INTO studentskills VALUES ('12             ', 'Python');
INSERT INTO studentskills VALUES ('71             ', 'DBMS');
INSERT INTO studentskills VALUES ('32             ', 'MATLAB');
INSERT INTO studentskills VALUES ('91             ', 'Hadoop');
INSERT INTO studentskills VALUES ('35             ', 'Networking Tools');
INSERT INTO studentskills VALUES ('2              ', 'Data Structures');
INSERT INTO studentskills VALUES ('89             ', 'C');
INSERT INTO studentskills VALUES ('30             ', 'C');
INSERT INTO studentskills VALUES ('45             ', 'Data Structures');
INSERT INTO studentskills VALUES ('79             ', 'Java');
INSERT INTO studentskills VALUES ('9              ', 'Cryptography');
INSERT INTO studentskills VALUES ('40             ', 'OpenMP');
INSERT INTO studentskills VALUES ('31             ', 'Linux Tools');
INSERT INTO studentskills VALUES ('57             ', 'Cryptography');
INSERT INTO studentskills VALUES ('22             ', 'Networking Tools');
INSERT INTO studentskills VALUES ('28             ', 'Microcontroller');
INSERT INTO studentskills VALUES ('60             ', 'MATLAB');
INSERT INTO studentskills VALUES ('24             ', 'C');
INSERT INTO studentskills VALUES ('86             ', 'Python');
INSERT INTO studentskills VALUES ('73             ', 'Microcontroller');
INSERT INTO studentskills VALUES ('68             ', 'Java');
INSERT INTO studentskills VALUES ('95             ', 'DBMS');
INSERT INTO studentskills VALUES ('64             ', 'Python');
INSERT INTO studentskills VALUES ('76             ', 'Java');
INSERT INTO studentskills VALUES ('49             ', 'OpenMP');
INSERT INTO studentskills VALUES ('45             ', 'C');
INSERT INTO studentskills VALUES ('100            ', 'DBMS');
INSERT INTO studentskills VALUES ('42             ', 'Python');
INSERT INTO studentskills VALUES ('61             ', 'Microcontroller');
INSERT INTO studentskills VALUES ('53             ', 'Cryptography');
INSERT INTO studentskills VALUES ('29             ', 'DBMS');
INSERT INTO studentskills VALUES ('56             ', 'Python');
INSERT INTO studentskills VALUES ('44             ', 'Android');
INSERT INTO studentskills VALUES ('15             ', 'System Softwares');
INSERT INTO studentskills VALUES ('59             ', 'Android');
INSERT INTO studentskills VALUES ('87             ', 'MPI');
INSERT INTO studentskills VALUES ('33             ', 'MATLAB');
INSERT INTO studentskills VALUES ('35             ', 'Hadoop');
INSERT INTO studentskills VALUES ('24             ', 'Python');
INSERT INTO studentskills VALUES ('7              ', 'Data Structures');
INSERT INTO studentskills VALUES ('93             ', 'Android');
INSERT INTO studentskills VALUES ('51             ', 'MATLAB');
INSERT INTO studentskills VALUES ('89             ', 'Python');
INSERT INTO studentskills VALUES ('55             ', 'MPI');
INSERT INTO studentskills VALUES ('27             ', 'Cryptography');
INSERT INTO studentskills VALUES ('17             ', 'DBMS');
INSERT INTO studentskills VALUES ('88             ', 'OpenMP');
INSERT INTO studentskills VALUES ('92             ', 'System Softwares');
INSERT INTO studentskills VALUES ('39             ', 'Linux Tools');
INSERT INTO studentskills VALUES ('46             ', 'Microcontroller');
INSERT INTO studentskills VALUES ('7              ', 'Hadoop');
INSERT INTO studentskills VALUES ('58             ', 'Java');
INSERT INTO studentskills VALUES ('80             ', 'Hadoop');
INSERT INTO studentskills VALUES ('79             ', 'Android');
INSERT INTO studentskills VALUES ('88             ', 'System Softwares');
INSERT INTO studentskills VALUES ('89             ', 'MPI');
INSERT INTO studentskills VALUES ('44             ', 'Cryptography');
INSERT INTO studentskills VALUES ('92             ', 'OpenMP');
INSERT INTO studentskills VALUES ('24             ', 'Networking Tools');
INSERT INTO studentskills VALUES ('19             ', 'Microcontroller');
INSERT INTO studentskills VALUES ('74             ', 'Data Structures');
INSERT INTO studentskills VALUES ('11             ', 'Data Structures');
INSERT INTO studentskills VALUES ('23             ', 'OpenMP');
INSERT INTO studentskills VALUES ('94             ', 'Data Structures');
INSERT INTO studentskills VALUES ('48             ', 'Java');
INSERT INTO studentskills VALUES ('82             ', 'Linux Tools');
