INSERT INTO studentinterests VALUES ('28             ', 'Robotics');
INSERT INTO studentinterests VALUES ('92             ', 'Algorithms');
INSERT INTO studentinterests VALUES ('1              ', 'Algorithms');
INSERT INTO studentinterests VALUES ('85             ', 'Image Processing');
INSERT INTO studentinterests VALUES ('98             ', 'Electronics');
INSERT INTO studentinterests VALUES ('57             ', 'Internet of Things');
INSERT INTO studentinterests VALUES ('38             ', 'Image Processing');
INSERT INTO studentinterests VALUES ('76             ', 'Image Processing');
INSERT INTO studentinterests VALUES ('97             ', 'Satellite Communication');
INSERT INTO studentinterests VALUES ('63             ', 'Robotics');
INSERT INTO studentinterests VALUES ('17             ', 'Embedded Hardware Design');
INSERT INTO studentinterests VALUES ('97             ', 'Signal Processing');
INSERT INTO studentinterests VALUES ('13             ', 'Mobile Development');
INSERT INTO studentinterests VALUES ('94             ', 'HPC');
INSERT INTO studentinterests VALUES ('41             ', 'Economics');
INSERT INTO studentinterests VALUES ('35             ', 'Computational Physics');
INSERT INTO studentinterests VALUES ('45             ', 'Data Science');
INSERT INTO studentinterests VALUES ('80             ', 'Robotics');
INSERT INTO studentinterests VALUES ('25             ', 'Satellite Communication');
INSERT INTO studentinterests VALUES ('44             ', 'Image Processing');
INSERT INTO studentinterests VALUES ('50             ', 'Robotics');
INSERT INTO studentinterests VALUES ('78             ', 'Computational Physics');
INSERT INTO studentinterests VALUES ('89             ', 'Machine Learning');
INSERT INTO studentinterests VALUES ('55             ', 'Embedded Hardware Design');
INSERT INTO studentinterests VALUES ('7              ', 'Applied Mathematics');
INSERT INTO studentinterests VALUES ('8              ', 'Image Processing');
INSERT INTO studentinterests VALUES ('66             ', 'Image Processing');
INSERT INTO studentinterests VALUES ('35             ', 'Economics');
INSERT INTO studentinterests VALUES ('45             ', 'Applied Mathematics');
INSERT INTO studentinterests VALUES ('82             ', 'Electronics');
INSERT INTO studentinterests VALUES ('61             ', 'Economics');
INSERT INTO studentinterests VALUES ('78             ', 'HPC');
INSERT INTO studentinterests VALUES ('18             ', 'Image Processing');
INSERT INTO studentinterests VALUES ('14             ', 'Robotics');
INSERT INTO studentinterests VALUES ('70             ', 'Embedded Hardware Design');
INSERT INTO studentinterests VALUES ('10             ', 'Internet of Things');
INSERT INTO studentinterests VALUES ('97             ', 'Robotics');
INSERT INTO studentinterests VALUES ('35             ', 'Algorithms');
INSERT INTO studentinterests VALUES ('40             ', 'Computational Physics');
INSERT INTO studentinterests VALUES ('65             ', 'Economics');
INSERT INTO studentinterests VALUES ('5              ', 'Applied Mathematics');
INSERT INTO studentinterests VALUES ('92             ', 'Electronics');
INSERT INTO studentinterests VALUES ('79             ', 'Robotics');
INSERT INTO studentinterests VALUES ('69             ', 'Signal Processing');
INSERT INTO studentinterests VALUES ('22             ', 'Mobile Development');
INSERT INTO studentinterests VALUES ('16             ', 'Image Processing');
INSERT INTO studentinterests VALUES ('50             ', 'Internet of Things');
INSERT INTO studentinterests VALUES ('55             ', 'Internet of Things');
INSERT INTO studentinterests VALUES ('46             ', 'Robotics');
INSERT INTO studentinterests VALUES ('77             ', 'Internet of Things');
INSERT INTO studentinterests VALUES ('36             ', 'Data Science');
INSERT INTO studentinterests VALUES ('78             ', 'Internet of Things');
INSERT INTO studentinterests VALUES ('73             ', 'Machine Learning');
INSERT INTO studentinterests VALUES ('97             ', 'Electronics');
INSERT INTO studentinterests VALUES ('95             ', 'Image Processing');
INSERT INTO studentinterests VALUES ('50             ', 'Embedded Hardware Design');
INSERT INTO studentinterests VALUES ('52             ', 'Data Science');
INSERT INTO studentinterests VALUES ('1              ', 'Satellite Communication');
INSERT INTO studentinterests VALUES ('31             ', 'Internet of Things');
INSERT INTO studentinterests VALUES ('70             ', 'Internet of Things');
INSERT INTO studentinterests VALUES ('31             ', 'Embedded Hardware Design');
INSERT INTO studentinterests VALUES ('55             ', 'Data Science');
INSERT INTO studentinterests VALUES ('97             ', 'Applied Mathematics');
INSERT INTO studentinterests VALUES ('34             ', 'Applied Mathematics');
INSERT INTO studentinterests VALUES ('6              ', 'Machine Learning');
INSERT INTO studentinterests VALUES ('21             ', 'Electronics');
INSERT INTO studentinterests VALUES ('67             ', 'Satellite Communication');
INSERT INTO studentinterests VALUES ('95             ', 'Economics');
INSERT INTO studentinterests VALUES ('60             ', 'Mobile Development');
INSERT INTO studentinterests VALUES ('58             ', 'Computational Physics');
INSERT INTO studentinterests VALUES ('46             ', 'Image Processing');
INSERT INTO studentinterests VALUES ('60             ', 'Algorithms');
INSERT INTO studentinterests VALUES ('13             ', 'Image Processing');
INSERT INTO studentinterests VALUES ('40             ', 'HPC');
INSERT INTO studentinterests VALUES ('53             ', 'Satellite Communication');
INSERT INTO studentinterests VALUES ('77             ', 'Signal Processing');
INSERT INTO studentinterests VALUES ('31             ', 'Data Science');
INSERT INTO studentinterests VALUES ('71             ', 'Satellite Communication');
INSERT INTO studentinterests VALUES ('37             ', 'Data Science');
INSERT INTO studentinterests VALUES ('92             ', 'Applied Mathematics');
INSERT INTO studentinterests VALUES ('5              ', 'Computational Physics');
INSERT INTO studentinterests VALUES ('10             ', 'Signal Processing');
INSERT INTO studentinterests VALUES ('56             ', 'Applied Mathematics');
INSERT INTO studentinterests VALUES ('1              ', 'Computational Physics');
INSERT INTO studentinterests VALUES ('77             ', 'Computational Physics');
INSERT INTO studentinterests VALUES ('93             ', 'Algorithms');
INSERT INTO studentinterests VALUES ('79             ', 'Data Science');
INSERT INTO studentinterests VALUES ('7              ', 'Image Processing');
INSERT INTO studentinterests VALUES ('89             ', 'Satellite Communication');
INSERT INTO studentinterests VALUES ('36             ', 'Algorithms');
INSERT INTO studentinterests VALUES ('74             ', 'Signal Processing');
INSERT INTO studentinterests VALUES ('51             ', 'Robotics');
INSERT INTO studentinterests VALUES ('81             ', 'Robotics');
INSERT INTO studentinterests VALUES ('87             ', 'Electronics');
INSERT INTO studentinterests VALUES ('21             ', 'HPC');
INSERT INTO studentinterests VALUES ('81             ', 'Signal Processing');
INSERT INTO studentinterests VALUES ('5              ', 'Embedded Hardware Design');
INSERT INTO studentinterests VALUES ('64             ', 'Machine Learning');
